# Generated by Django 5.1.1 on 2024-09-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='autumn',
            field=models.CharField(blank=True, choices=[('2B', '2Б'), ('3B', '3Б'), ('1A', '1А'), ('3A', '3А'), ('2A', '2А'), ('1B', '1Б')], default='1A', max_length=2, null=True, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='spring',
            field=models.CharField(blank=True, choices=[('2B', '2Б'), ('3B', '3Б'), ('1A', '1А'), ('3A', '3А'), ('2A', '2А'), ('1B', '1Б')], default='1A', max_length=2, null=True, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='summer',
            field=models.CharField(blank=True, choices=[('2B', '2Б'), ('3B', '3Б'), ('1A', '1А'), ('3A', '3А'), ('2A', '2А'), ('1B', '1Б')], default='1A', max_length=2, null=True, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='winter',
            field=models.CharField(blank=True, choices=[('2B', '2Б'), ('3B', '3Б'), ('1A', '1А'), ('3A', '3А'), ('2A', '2А'), ('1B', '1Б')], default='1A', max_length=2, null=True, verbose_name='Зима'),
        ),
    ]
